import AppKit
import Foundation

public final class ClipboardNormalizer {
    public init() {}

    public func capture(
        from pasteboard: NSPasteboard = .general,
        sourceBundleId: String?,
        sourceName: String?,
        settings: AppSettings,
        privacyMatcher: PrivacyRuleMatcher
    ) -> PendingClipboardItem? {
        guard let pasteboardItems = pasteboard.pasteboardItems, !pasteboardItems.isEmpty else {
            return nil
        }

        let typeIdentifiers = pasteboardItems.flatMap { $0.types.map(\.rawValue) }
        let preview = previewText(from: pasteboardItems)

        if privacyMatcher.shouldSkip(
            sourceBundleId: sourceBundleId,
            typeIdentifiers: typeIdentifiers,
            previewText: preview
        ) {
            return nil
        }

        var payloads: [ClipboardPayload] = []
        var totalSize = 0
        let preferredTypes = orderedPasteboardTypes(from: pasteboardItems)

        for item in pasteboardItems {
            for type in preferredTypes where item.types.contains(type) {
                guard let data = item.data(forType: type), !data.isEmpty else {
                    continue
                }
                if payloads.contains(where: { $0.uti == type.rawValue && $0.data == data }) {
                    continue
                }
                totalSize += data.count
                if totalSize > settings.largeItemLimit {
                    return nil
                }
                payloads.append(ClipboardPayload(uti: type.rawValue, data: data))
            }
        }

        guard !payloads.isEmpty else {
            return nil
        }

        let primaryType = Self.primaryType(typeIdentifiers: typeIdentifiers, previewText: preview)
        let item = ClipboardItem(
            sourceBundleId: sourceBundleId,
            sourceName: sourceName,
            primaryType: primaryType,
            previewText: Self.makePreviewText(preview, primaryType: primaryType, payloads: payloads),
            contentHash: Hashing.contentHash(payloads: payloads),
            isSensitive: false,
            blobRefs: []
        )
        return PendingClipboardItem(item: item, payloads: payloads)
    }

    public static func primaryType(typeIdentifiers: [String], previewText: String?) -> String {
        let joined = typeIdentifiers.joined(separator: " ").lowercased()
        if joined.contains("file-url") || joined.contains("public.file-url") {
            return ClipboardTypeFilter.file.rawValue
        }
        if joined.contains("public.url") {
            return ClipboardTypeFilter.url.rawValue
        }
        if joined.contains("public.png") || joined.contains("public.tiff") || joined.contains("image") {
            return ClipboardTypeFilter.image.rawValue
        }
        if joined.contains("pdf") {
            return ClipboardTypeFilter.pdf.rawValue
        }
        if joined.contains("rtf") || joined.contains("html") {
            return ClipboardTypeFilter.richText.rawValue
        }
        if joined.contains("color") {
            return ClipboardTypeFilter.color.rawValue
        }
        if let previewText, looksLikeCode(previewText) {
            return ClipboardTypeFilter.code.rawValue
        }
        if let previewText, URL(string: previewText.trimmingCharacters(in: .whitespacesAndNewlines))?.scheme != nil {
            return ClipboardTypeFilter.url.rawValue
        }
        return ClipboardTypeFilter.text.rawValue
    }

    private func orderedPasteboardTypes(from items: [NSPasteboardItem]) -> [NSPasteboard.PasteboardType] {
        let preferred = [
            NSPasteboard.PasteboardType.string,
            NSPasteboard.PasteboardType.URL,
            NSPasteboard.PasteboardType.fileURL,
            NSPasteboard.PasteboardType.html,
            NSPasteboard.PasteboardType.rtf,
            NSPasteboard.PasteboardType("com.adobe.pdf"),
            NSPasteboard.PasteboardType.png,
            NSPasteboard.PasteboardType.tiff,
            NSPasteboard.PasteboardType.color
        ]

        var ordered: [NSPasteboard.PasteboardType] = []
        for type in preferred where items.contains(where: { $0.types.contains(type) }) {
            ordered.append(type)
        }

        let remaining = items.flatMap(\.types)
            .filter { !ordered.contains($0) }
            .filter { !$0.rawValue.lowercased().contains("transienttype") }
            .filter { !$0.rawValue.lowercased().contains("concealedtype") }
            .filter { !$0.rawValue.lowercased().contains("autogeneratedtype") }
        for type in remaining where !ordered.contains(type) {
            ordered.append(type)
        }
        return ordered
    }

    private func previewText(from items: [NSPasteboardItem]) -> String? {
        for item in items {
            if let string = item.string(forType: .string), !string.isEmpty {
                return string
            }
            if let url = item.string(forType: .URL), !url.isEmpty {
                return url
            }
            if let file = item.string(forType: .fileURL), !file.isEmpty {
                return URL(string: file)?.path ?? file
            }
            if let html = item.string(forType: .html), !html.isEmpty {
                return Self.stripHTML(html)
            }
        }
        return nil
    }

    private static func makePreviewText(_ preview: String?, primaryType: String, payloads: [ClipboardPayload]) -> String {
        if let preview = preview?.trimmingCharacters(in: .whitespacesAndNewlines), !preview.isEmpty {
            return String(preview.prefix(1_000))
        }

        switch primaryType {
        case ClipboardTypeFilter.image.rawValue:
            return "Image"
        case ClipboardTypeFilter.pdf.rawValue:
            return "PDF document"
        case ClipboardTypeFilter.file.rawValue:
            return "File"
        case ClipboardTypeFilter.color.rawValue:
            return "Color"
        default:
            let types = payloads.map(\.uti).joined(separator: ", ")
            return types.isEmpty ? "Clipboard item" : types
        }
    }

    private static func stripHTML(_ html: String) -> String {
        guard let data = html.data(using: .utf8),
              let attributed = try? NSAttributedString(
                data: data,
                options: [
                    .documentType: NSAttributedString.DocumentType.html,
                    .characterEncoding: String.Encoding.utf8.rawValue
                ],
                documentAttributes: nil
              )
        else {
            return html.replacingOccurrences(of: "<[^>]+>", with: " ", options: .regularExpression)
        }
        return attributed.string
    }

    private static func looksLikeCode(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > 12 else {
            return false
        }
        let markers = ["func ", "let ", "var ", "class ", "struct ", "import ", "{", "};", "=>", "</", "#include", "SELECT "]
        let hits = markers.filter { trimmed.localizedCaseInsensitiveContains($0) }.count
        return hits >= 2 || trimmed.split(separator: "\n").count > 4 && trimmed.contains("{")
    }
}
