import Foundation

public struct PrivacyRuleMatcher {
    public static let defaultIgnoredBundleIds = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.dashlane.dashlane-desktop",
        "com.lastpass.LastPass",
        "com.apple.keychainaccess"
    ]

    public static let defaultRules: [PrivacyRule] = [
        PrivacyRule(kind: .type, pattern: "org.nspasteboard.ConcealedType"),
        PrivacyRule(kind: .type, pattern: "org.nspasteboard.TransientType"),
        PrivacyRule(kind: .type, pattern: "org.nspasteboard.AutoGeneratedType")
    ]

    private let ignoredBundleIds: Set<String>
    private let rules: [PrivacyRule]

    public init(settings: AppSettings) {
        self.ignoredBundleIds = Set(settings.ignoredBundleIds)
        self.rules = settings.privacyRules.filter(\.enabled)
    }

    public init(ignoredBundleIds: [String], rules: [PrivacyRule]) {
        self.ignoredBundleIds = Set(ignoredBundleIds)
        self.rules = rules.filter(\.enabled)
    }

    public func shouldSkip(
        sourceBundleId: String?,
        typeIdentifiers: [String],
        previewText: String?,
        windowTitle: String? = nil
    ) -> Bool {
        if let sourceBundleId, ignoredBundleIds.contains(sourceBundleId) {
            return true
        }

        for type in typeIdentifiers where isConcealedOrTransient(type) {
            return true
        }

        for rule in rules {
            switch rule.kind {
            case .app:
                if let sourceBundleId, sourceBundleId.localizedCaseInsensitiveContains(rule.pattern) {
                    return rule.action == .skip
                }
            case .type:
                if typeIdentifiers.contains(where: { $0.localizedCaseInsensitiveContains(rule.pattern) }) {
                    return rule.action == .skip
                }
            case .regex:
                if let previewText, matchesRegex(rule.pattern, in: previewText) {
                    return rule.action == .skip
                }
            case .windowTitle:
                if let windowTitle, windowTitle.localizedCaseInsensitiveContains(rule.pattern) {
                    return rule.action == .skip
                }
            }
        }

        return false
    }

    private func isConcealedOrTransient(_ type: String) -> Bool {
        let lowered = type.lowercased()
        return lowered.contains("concealedtype")
            || lowered.contains("transienttype")
            || lowered.contains("autogeneratedtype")
    }

    private func matchesRegex(_ pattern: String, in text: String) -> Bool {
        do {
            let regex = try NSRegularExpression(pattern: pattern, options: [.caseInsensitive])
            let range = NSRange(text.startIndex..<text.endIndex, in: text)
            return regex.firstMatch(in: text, range: range) != nil
        } catch {
            return false
        }
    }
}
